rabbitmq:
  # These values can be overridden by environment variables
  uri: amqp://guest:guest@rabbitmq:5672/
  queue_name: mysql.events
  exchange_name: mysql-events
  exchange_type: topic
  routing_key: "mysql.*"  # Listen to all topics starting with mysql.
  # Specific queues for db.table combinations
  specific_queues:
    - "inventory.customers.queue"
    - "inventory.orders.queue"
    - "ecommerce.products.queue"
    - "ecommerce.categories.queue"

mongodb:
  # These values can be overridden by environment variables
  - uri: mongodb://admin:admin@mongodb1:27017/
    database: cdc_data
    collection_prefix: mysql
  - uri: mongodb://admin:admin@mongodb2:27017/
    database: cdc_data
    collection_prefix: mysql
