FROM golang:1.21-alpine

WORKDIR /app

# Install required dependencies for building the Go application
RUN apk add --no-cache git gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./
RUN go build -o data-generator

CMD ["./data-generator"]
